### ISSUE TITLE
adding new note - error

### ISSUE THREAD

**Issue by georgesuba** [virtualmin/virtualmin-notes#1]
when adding new note on lates virtualmin I will get error - missing content headers.. updated debian 8.

**Comment by georgesuba** [comment]
no reply... uh

**Comment by swelljoe** [comment]
Is it still an issue you're seeing? If so, can you send the miniserv.error log entries that happen at the time, if any? I'm not able to reproduce it on my system (though it seems like this module is pretty limited, and could use an upgrade if people actually want this functionality).

**Comment by georgesuba** [comment]
Hi Joe, well I did reinstall the plugin this morning but same issue, I had to remove it to make virtualmin working again... it could be possibly due to unsupported debian 9 version  (keep in mind this ticked was opened for debian 8 version).. actually best way to replicate would be installing it into your virtualmin.. and you could see it for your self.... notes would be awesome addition to virtualmin so no external notes... you know what I mean.

also i am not happy that simple readme.md is not included which as programmer I understand but still for other folks - would be possible to add readme.md file with some info how to install it or... you know.. 

many thanks.

**Comment by swelljoe** [comment]
Oh, you installed directly from github! So, that's actually trickier than it looks. 

Use your system package manager to install the package in our repos, if you're not developing with it. To install a Webmin module from a source repo like this requires manually copying in the right config file, possibly changing the perl path to suit your system, and making it available to users in the Webmin Users module. When you install via the package manager or via Webmin itself, all of that gets done automatically.

This module is in both the yum (wbm-virtualmin-notes) and apt-get (webmin-virtualmin-notes) repositories.

I haven't written up docs for everything yet, as I'm still working on just getting stuff out into the world in public repositories. The stuff I've been focusing most of my attention on are modules and programs that have outside developer interest, like virtualmin-install and Virtualmin itself. All of the modules that I've released onto github repos have been in our software repositories for ages. github isn't really how we're setup to distribute packages (yet).

**Comment by georgesuba** [comment]
ah i see, i did not know it could be installed via apt-get.. thanks for all information.
